// <auto-generated />
namespace FundSharer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AdminAccountDeprecated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdminAccountDeprecated));
        
        string IMigrationMetadata.Id
        {
            get { return "201707021450151_AdminAccountDeprecated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
